### ISSUE TITLE
c++ 不支持首拼匹配，只能用全拼！

### ISSUE THREAD

**Issue by o-3-o** [stratosblue/ChinesePinyinIntelliSenseExtender#10]
你的这个插件很好用，非常感谢您的贡献，但是我在VS2022的C++环境中测试了了可以正常使用，
就是无法使用首拼去匹配，只能用全拼，
比如  "文本" 只能用 "wenben" 匹配 不能用"wb"匹配。

**Comment by stratosblue** [comment]
嗯。。。这块暂时感觉有点难度。。。有空了我再尝试尝试。。。。

**Comment by o-3-o** [comment]
目前有个离谱的解决方法就是将每个单词的拼音单独放置可以实现，就是有个缺点会重复显示多次变量。

如 ：
中 z
中zh
中 zho
中 zhon
中 zhong
文 w
文 we
文 wen

这样打'zw' 'zhw' 'zhongw'的时候就会匹配了，只是重复显示的词库太多了 哈哈

**Comment by stratosblue** [comment]
你还别说，我想过添加一个首字母的候选项。。。不过有点草率了，哈哈哈哈

**Comment by o-3-o** [comment]
大佬，抽空更新更新哈~ 太实用了

**Comment by stratosblue** [comment]
@o-3-o 这个要花时间研究，相关文档好像不多，最近工作忙，暂时没法抽出时间搞😂😂😂

**Comment by o-3-o** [comment]
@stratosblue 

![play](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/51990072/56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1)

目前还有两个问题，

1：当输入 int 再按空格时  会自动选择当前预选词，(空格键得效果变成和回车键一样)

2:  显示的预选词和实际的词不一样，比如输入 int 按下回车 打印出来的是别的词

**Comment by stratosblue** [comment]
> @stratosblue
> 
> ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM) [ ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM) ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM) [ ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> 
> 目前还有两个问题，
> 
> 1：当输入 int 再按空格时 会自动选择当前预选词，(空格键得效果变成和回车键一样)
> 
> 2: 显示的预选词和实际的词不一样，比如输入 int 按下回车 打印出来的是别的词

感谢测试，已尝试修正并发布1.3.3，麻烦更新后测试一下

**Comment by o-3-o** [comment]
> > @stratosblue
> > ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >       
> >         [
> >           
> >             ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >           
> >         ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM) ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >       
> >         [
> >           
> >             ![play](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >           
> >         ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/51990072/329658134-56bff3cb-bfc6-4259-afd7-4a4d89a3a9f1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDIyMDksIm5iZiI6MTcxNTQwMTkwOSwicGF0aCI6Ii81MTk5MDA3Mi8zMjk2NTgxMzQtNTZiZmYzY2ItYmZjNi00MjU5LWFmZDctNGE0ZDg5YTNhOWYxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTJjZjMxYzQwOTA1NjQxM2UwZmM3MTQ0YTk5ODUyZTg0OThlMzNmOGYzYjBlODkxYzc0MWM3OTg0NmNhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPG6jl2ZoBEoUnVSk-cFFs1C00KwtiSLihtf8GxOmFM)
> > 目前还有两个问题，
> > 1：当输入 int 再按空格时 会自动选择当前预选词，(空格键得效果变成和回车键一样)
> > 2: 显示的预选词和实际的词不一样，比如输入 int 按下回车 打印出来的是别的词
> 
> 感谢测试，已尝试修正并发布1.3.3，麻烦更新后测试一下

非常感谢修正, 已测试目前没有问题，后续有问题我再来反馈，非常感谢，辛苦了！
