### ISSUE TITLE
编译出错：Extension 'ChinesePinyinIntelliSenseExtender.4293B766-9575-4472-B6F0-98BD86737E0D' could not be found. Please make sure the extension has been installed.	

### ISSUE THREAD

**Issue by soeasycode** [stratosblue/ChinesePinyinIntelliSenseExtender#12]
你好，请教下，我用2022重新编译会提示出错是什么原因，谢谢
![捕获](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/168963110/34a4b79f-5175-4914-8286-952f28703fae)

**Comment by stratosblue** [comment]
SDK安装了吗？
![图片](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/20887303/c1eddafc-8741-4db1-abb1-3ad325800938)

**Comment by soeasycode** [comment]
安装了
![Uploading 捕获.PNG…]()

**Comment by stratosblue** [comment]
我没有遇到这个问题，不过搜到了一些类似情况，你可以参考下，大概可以试试
- 重置VisualStudio实验实例
- 增加拓展的版本号

https://stackoverflow.com/questions/32870002/extension-could-not-be-found-please-make-sure-the-extension-has-been-installed
https://github.com/modelsbuilder/ModelsBuilder.Original/issues/52

**Comment by soeasycode** [comment]
好的，我试下，谢谢

**Comment by soeasycode** [comment]
按照你的方法已经可以正常生成了，但是安装以后出现这个错误
![Uploading 捕获.PNG…]()

**Comment by soeasycode** [comment]
直接下载你编译好的扩展没有这个错误

**Comment by stratosblue** [comment]
图裂了。。看不到。。。

**Comment by soeasycode** [comment]
![捕获](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/168963110/4dfb8946-9c46-466a-b839-6e4ae7eb4792)

**Comment by soeasycode** [comment]
这个是什么情况

**Comment by stratosblue** [comment]
看起来是字典文件没对。搞忘做正确性检查了。
字典文件没有直接包含在项目里面，是以 `git submodule` 引入的，你确认下有没有初始化。
根目录下有脚本 `init-gitmodules.ps1`

**Comment by soeasycode** [comment]
重新运行脚本下载了字典就正常了，我先看看代码，不懂的再请教你，非常感谢！
