### ISSUE TITLE
maui框架上可以用吗？

### ISSUE THREAD

**Issue by zozero** [stratosblue/ChinesePinyinIntelliSenseExtender#4]
我尝试安装，但没有起到效果

**Comment by stratosblue** [comment]
@zozero 
你应该说的是maui的xmal编辑器吧？我试了一下，xmal编辑器是基于 `ICompletionSource` 的，暂时不支持，非常抱歉。。。

**Comment by zozero** [comment]
.cs文件内也不好使，我不知道是什么原因，我感觉我安装的根本没效果。需要额外做些其他的设置吗？

**Comment by stratosblue** [comment]
尝试重启之后看看有没有生效，没有的话在拓展列表里面禁用拓展，重启VS，再试试原有的代码提示有没有恢复。如果禁用拓展之后提示恢复了，那可能是有冲突，麻烦贴一下VS版本

**Comment by zozero** [comment]
**这是我安装的产品信息，禁用拓展后提示恢复了。拓展是否崩溃我没有注意到，并没要看到什么错误提示。**

Microsoft Visual Studio Community 2022
版本 17.5.0 Preview 1.0
VisualStudio.17.Preview/17.5.0-pre.1.0+33103.201
Microsoft .NET Framework
版本 4.8.09032

已安装的版本: Community

Visual C++ 2022   00482-90000-00000-AA126
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.90.43013
ASP.NET and Web Tools

Azure 应用服务工具 3.0.0 版   17.5.90.43013
Azure 应用服务工具 3.0.0 版

C# 工具   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

CodeMaid   12.0
CodeMaid 是一个开源Visual Studio 扩展, 用于清理和简化我们的 C#、C++、F#、VB、PHP、PowerShell、R、JSON、XAML、XML、ASP、HTML、CSS、LESS、SCSS、JavaScript 和TypeScript编码。

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.0 (52dce31)
Support for debugging Mono processes with Visual Studio.

NuGet 包管理器   6.5.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 https://docs.nuget.org/

NVIDIA CUDA 11.6 Wizards   11.6
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA CUDA 11.8 Wizards   11.8
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2022.3.0.22245
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2022.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•Icons from Axialis Software used under the licensing terms found here: www.axialis.com
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•Breakpad Copyright ©2006, Google Inc. All rights reserved.
•The OpenGL Extension Wrangler Library
Copyright ©2008-2016, Nigel Stewart (nigels@users.sourceforge.net), Copyright ©2002-2008, Milan Ikits (milan.ikits@ieee.org), Copyright ©2002-2008, Marcelo E. Magallon (mmagallo@debian.org), Copyright ©2002, Lev Povalahev. 
All rights reserved. 
•LIBSSH2 Copyright ©2004-2007 Sara Golemon (sarag@libssh2.org), Copyright ©2005,2006 Mikhail Gusarov (dottedmag@dottedmag.net),Copyright ©2006-2007 The Written Word, Inc.,Copyright ©2007 Eli Fant (elifantu@mail.ru),Copyright ©2009-2014 Daniel Stenberg., Copyright ©2008, 2009 Simon Josefsson.
All rights reserved. 
•Protobuf Copyright ©2014, Google Inc. All rights reserved.
•xxHASH Library Copyright ©2012-2014, Yann Collet. All rights reserved. 
•FMT Copyright ©2012 - 2016, Victor Zverovich 
•Font Awesome Copyright 2018 Fonticons, Inc. 
•ELF Definitions Copyright (c) 2010 Joseph Koshy, All rights reserved.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2022.3.0.22245
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

Razor (ASP.NET Core)   17.0.0.2255201+5530de5c8323cd1ecacb497bbab5637907d0fc02
提供 ASP.NET Core Razor 的语言服务。

TypeScript Tools   17.0.11026.2001
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.4.212
Add color to your Visual Studio editor!

Visual Basic 工具   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
IDE 中使用的 Visual Basic 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

Visual F# Tools   17.5.0-beta.22525.1+90f5b1ed0befe8337b923860d29dcd62d4735aef
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
Visual Studio 的 AI 协助开发。

VisualStudio.DeviceLog   1.0
有关我的包的信息

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage 扩展   1.0
VSPackage Visual Studio 扩展详细信息

VsTranslator Extension   1.0
VsTranslator Visual Studio Extension Detailed Info

Xamarin   17.5.0.66 (main@fb92eb2)
用于启用 Xamarin.iOS 和 Xamarin.Android 的开发的 Visual Studio 扩展。

Xamarin Designer   17.5.1.13 (remotes/origin/d17-5@14bdde937f)
用于在 Visual Studio 中启用 Xamarin Designer 工具的 Visual Studio 扩展。

Xamarin Templates   17.5.3 (3c53880)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.92 (3dd3dc52c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

适用于 Google Test 的测试适配器   1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

用于 Boost.Test 的测试适配器   1.0
通过针对 Boost.Test 编写的单元测试启用 Visual Studio 测试工具。扩展安装目录中提供用户条款和第三方通知。

**Comment by stratosblue** [comment]
感谢提供信息，我抽个空排查一下，第一感觉可能和VS的预览版本有关。。。

**Comment by stratosblue** [comment]
@zozero 发了个新版本，你再试下呢

**Comment by zozero** [comment]
我尝试了一下，在我禁用ReSharper后可以正常使用，很强。
ReSharper这个插件我也是使用试用版本的，不过也快过期了。
可以冒昧的问一下，能不能介绍一个产品给我替代它？
CodeRush我有试过但用的不是很习惯，主要是代码提示如果只输入一半，切走后，继续往下输入就没有提示了，我之所以会转切走是因为我还在学习c#这门语言，需要看看教程。

**Comment by stratosblue** [comment]
看样子可能和ReSharper存在兼容性问题,我抽空再处理下;

推荐类似的产品就有点为难我了。。。我没有使用过ReSharper，VS自带的功能满足个人需求。。。

至于补全上下文焦点丢失后消失的问题，可以试试能不能快捷键再次唤起，具体的快捷键可以在设置的 "环境"->"键盘" 里面查找 "编辑.完成单词" 进行查看或设置。

**Comment by stratosblue** [comment]
看起来reshaper有自己的完成逻辑，VS的完成逻辑没有触发，不好兼容了

**Comment by zozero** [comment]
我直接放弃了reshaper，还是你这个插件香：）
