### ISSUE TITLE
可能支持日语假名和日语汉字么

### ISSUE THREAD

**Issue by ZjzMisaka** [stratosblue/ChinesePinyinIntelliSenseExtender#5]
罗马音->日文, 做法应该和拼音->中文挺相似的. 
日本人很喜欢用日语变量名, 深受其害. 如果能支持日语 (甚至其他表意文字), 应该会很实用.

**Comment by stratosblue** [comment]
可以的，现在只是为了稍微快一点，所以只判断了是中文再进行映射，如果所有字符都查映射字典，就可以通过自定义字典映射成任何东西，哈哈哈。有空我看看改一下

**Comment by stratosblue** [comment]
@ZjzMisaka 
发了新版本插件，你试试自定义字典文件，并设置预检查模式为None，看下能不能正常工作。

**Comment by ZjzMisaka** [comment]
> @ZjzMisaka 发了新版本插件，你试试自定义字典文件，并设置预检查模式为None，看下能不能正常工作。

似乎不行, 我把截图和文件传上来. 
![image](https://user-images.githubusercontent.com/16731853/206634119-2e545580-bbba-40de-bc3b-526cc96879dd.png)
![image](https://user-images.githubusercontent.com/16731853/206634062-1868e0f8-21f7-4342-89c2-01d96d30d9da.png)
![image](https://user-images.githubusercontent.com/16731853/206634284-c073a6f0-b2f2-4ece-896f-2e169f23d9d5.png)
[Custom.zip](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/files/10192170/Custom.zip)

**Comment by stratosblue** [comment]
@ZjzMisaka 
我试了文件，有内容不是 \t 分割的，我调整了一下，是可以按预期工作的

![3](https://user-images.githubusercontent.com/20887303/206638876-01c583a7-0a13-4ba6-8650-5776b71b1ea3.png)
![1](https://user-images.githubusercontent.com/20887303/206638901-1d2d60fe-1f48-4e0b-b464-8171c1a55d27.png)
![2](https://user-images.githubusercontent.com/20887303/206638917-4b446d1d-a4f9-46f1-b3bd-d796beabea5d.png)

[Custom.zip](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/files/10192324/Custom.zip)

你可以再试一下看看（我不确定日语环境是否有影响，理论上应该不会有影响。。。）

**Comment by ZjzMisaka** [comment]
> 

kanji.tsv确实有问题, 解决了就可以正常运行了. 
你考虑再建一个文件夹么放自定义的文件么, 我想把我的文件提交给你. 
制表符左侧可以支持多个字符么, 想要支持复杂点的日语训读的话要支持多个字符组成一个读音的, 我自己测试好像是不行的.

**Comment by stratosblue** [comment]
> 你考虑再建一个自定义的文件夹么, 我想把我的文件提交给你.

是指把词典内置到插件里面吗？可以，不过词典能完善一点最好，可以找找有没有类似 [rime](https://github.com/KyleBing/rime-wubi86-jidian) 的日语输入[词典](https://raw.githubusercontent.com/KyleBing/rime-wubi86-jidian/master/wubi86_jidian.dict.yaml)。

> 制表符左侧可以支持多个字符么, 想要支持复杂点的日语训读的话要支持多个字符组成一个读音的, 我自己测试好像是不行的.

支持多个字符的

![1](https://user-images.githubusercontent.com/20887303/206688837-51fca820-b134-43d5-8549-4e50a947900b.png)

![2](https://user-images.githubusercontent.com/20887303/206688850-235104ac-3d2a-447a-a627-3ffaf07bbcc5.png)

**Comment by ZjzMisaka** [comment]
我找到了比较完整的词典了, 并且用你的脚本转换, 试了一些词, 都挺有效的
因为没有合适的目录, 就先放issue里了. 
[ChinesePinyinIntelliSenseExtenderTsv.zip](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/files/10200518/ChinesePinyinIntelliSenseExtenderTsv.zip)

**Comment by stratosblue** [comment]
额。。。转换脚本是最开始支持字典文件的时候用的，那时候不支持多个字符映射才需要转换，并且对多音字的支持不太友好，现在是可以支持多字符的。能提供一下源文件吗？或者来源是公开的吗，可以贴个链接，我看下能不能直接使用，格式特殊的话可能需要改下代码。

**Comment by ZjzMisaka** [comment]
https://github.com/gkovacs/rime-japanese
来源在这

**Comment by stratosblue** [comment]
OK，我抽时间看看

**Comment by stratosblue** [comment]
@ZjzMisaka 
https://github.com/gkovacs/rime-japanese 这个字典非常全。。。但是太大了，单个字典文件几M到几十M，内置的话太大了。。。你可以下载里面的 `*.dict.yaml` 字典之后直接把文件路径添加到附加字典里面使用。

如果要内置的话，这个小字典感觉更适合一点 https://github.com/biopolyhedron/rime-jap-poly ，但我不确定效果怎么样。

**Comment by ZjzMisaka** [comment]
小字典也可以, 毕竟不是真的用来打字, 够用就行. 
另外我的本意其实不是直接内置到里边去, 而是当作类似于扩展之类的东西, 有用自取, 毕竟这个项目名字叫拼音扩展, 塞别的语言进去感觉破坏了这个项目.. 
我的本意是, 你可以新开一个文件夹但不包含在项目里, 讲究点的话扩展里还可以加一个默认的第三方字典文件夹, 或者干脆新开一个repo专门放第三方字典然后在readme里加一个链接即可. 
如果内置的话我当然更高兴, 我向公司里的人安利的时候就不用教他们做额外的设置了. 这个就看你决定了.

**Comment by stratosblue** [comment]
几十K，问题不大，先内置了，发了个新版本。后面如果还要加其它的再看看怎么处理了。哈哈哈哈
