### ISSUE TITLE
特定单词/汉字无法正常匹配

### ISSUE THREAD

**Issue by Miltomo** [stratosblue/ChinesePinyinIntelliSenseExtender#6]
### 无论是全拼还是首字母
![搜狗截图20240119174754](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/301966f9-7884-4600-8a09-3aae4b43ea03)
![搜狗截图20240119173940](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/d894a8cf-e9af-4e55-adaf-544a1c00f7a4)
- 值得注意的是结果有一个**[医WuShi]**
- 似乎是**“医”[Yi]**字无法被匹配
### 连带的部分匹配也变得无效
![搜狗截图20240119175726](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/027329bc-e58f-4261-a312-3030e0520ad7)

**Comment by stratosblue** [comment]
感谢反馈。。这是个BUG，已尝试修正并发布1.2.3版本，更新后再试试

**Comment by Miltomo** [comment]
已解决
