### ISSUE TITLE
不支持以英文开头的混合名称的变量名：e.g.[英文+中文]

### ISSUE THREAD

**Issue by Miltomo** [stratosblue/ChinesePinyinIntelliSenseExtender#7]
## 从英文开头输入
![搜狗截图20240124124054](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/8ea0cd65-7273-49c7-a64b-e80a80963fef)
![搜狗截图20240124124155](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/b2dcd72d-a32d-4e09-b385-1b496fbdfae7)
![搜狗截图20240124124310](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/b894a53c-58e5-4e13-b3e0-4c6203d25fc6)

## 按拼音输入
![搜狗截图20240124124118](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/f5defd93-cec2-4f73-a5d1-06bda87de493)
![搜狗截图20240124124226](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/1576f6bb-5081-4599-9977-71cfae209d7f)
![搜狗截图20240124124322](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/61451622/a963cd95-d5aa-4412-b128-1fd93f5e29ad)

- 估计其被视作纯英文变量

**Comment by Miltomo** [comment]
> 设置里面预检查模式调整为FullText试试
是VS的设置吗？没找到这个设置。扩展也没找到可以调的地方。

**Comment by stratosblue** [comment]
@Miltomo 
![图片](https://github.com/stratosblue/ChinesePinyinIntelliSenseExtender/assets/20887303/767e9c03-3949-4e1c-8803-aaff4d68d982)

**Comment by Miltomo** [comment]
可以了。很好用
